import fc from "fast-check";
import { describe, expect, it } from "vitest";

import { DefaultGameSessionFactory } from "./GameSessionFactory";
import { reduce } from "./reduce";
import { parseTimeLimit } from "./parseTimeLimit";
import { RecursiveBacktrackerGenerator } from "./RecursiveBacktrackerGenerator";
import {
  type GameState,
  type LostState,
  type Maze,
  type PlayingState,
  type Position,
  type TimeLimit,
  type WonState,
} from "./types";

/**
 * Property-based test for Correctness Property 3.
 *
 * Property 3 (design.md): *For any* prior game state and any valid
 * `GameConfig`, the session produced by `StartSession` places the avatar
 * exactly on the maze start cell, sets `remainingMs` to `timeLimit * 1000`,
 * has `timerStarted` false, has status `Playing`, and retains no avatar or
 * timer value from the prior state.
 *
 * Two independent paths are exercised, since both produce a fresh session:
 *   1. `DefaultGameSessionFactory.createSession(maze, timeLimit)` directly, and
 *   2. `reduce(priorState, { type: "StartSession", config })`, which builds the
 *      fresh session from the config while reusing the prior state's maze.
 *
 * The invariants checked for the fresh session are:
 *   - status is `"Playing"` (R6.2),
 *   - avatar is exactly `maze.start` (R1.2, R6.2),
 *   - `remainingMs === timeLimit * 1000` (R6.3, R7.4),
 *   - `timerStarted` is false — the timer is paused until the first move (R6.3),
 *   - `moveInProgress` is false — no animation carried in.
 *
 * "No leaked state" (R6.5) is proven by starting from an *arbitrary* prior
 * state — a mid-game `Playing` with a moved avatar and a partly-spent, running
 * timer, or a `Won`/`Lost` end state — and asserting the fresh session ignores
 * every prior value: the avatar returns to the start even when the prior avatar
 * was elsewhere, and the timer is refilled even when the prior one was drained.
 *
 * Determinism (testing steering): the maze is generated by
 * `RecursiveBacktrackerGenerator` driven by a seeded mulberry32 rng, and every
 * value (dimensions, seed, time limit, prior-state shape) is derived from
 * fast-check arbitraries — no `Math.random`, no wall-clock time. The property
 * runs a minimum of 100 iterations.
 *
 * _Validates: Requirements 1.2, 6.2, 6.3, 6.5, 7.4_
 */

const PROPERTY_MIN_RUNS = 100;
const MILLISECONDS_PER_SECOND = 1000;

/** Bounds for the player-specified time limit (seconds), per the domain model. */
const MIN_TIME_LIMIT_SECONDS = 30;
const MAX_TIME_LIMIT_SECONDS = 600;

/** Carve cells sit two grid steps apart, so useful mazes need at least 3 cells. */
const MIN_DIMENSION = 3;
const MAX_DIMENSION = 11;

/**
 * A tiny deterministic PRNG (mulberry32). Given the same seed it yields the
 * same sequence in `[0, 1)`, so maze generation depends only on its injected
 * inputs (no `Math.random`).
 */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const generator = new RecursiveBacktrackerGenerator();
const sessionFactory = new DefaultGameSessionFactory();

/** A valid branded time limit, produced through the only validator that brands one. */
function timeLimitOf(seconds: number): TimeLimit {
  const result = parseTimeLimit(seconds);
  if (!result.ok) {
    throw new Error(
      `test fixture expected a valid time limit, got ${seconds}`,
    );
  }
  return result.value;
}

/** Arbitrary valid maze: seeded recursive-backtracker over generated dimensions. */
const arbMaze: fc.Arbitrary<Maze> = fc
  .record({
    rows: fc.integer({ min: MIN_DIMENSION, max: MAX_DIMENSION }),
    columns: fc.integer({ min: MIN_DIMENSION, max: MAX_DIMENSION }),
    seed: fc.integer({ min: 0, max: 0xffffffff }),
  })
  .map(({ rows, columns, seed }) =>
    generator.generate(rows, columns, mulberry32(seed)),
  );

/** Arbitrary valid branded time limit via `parseTimeLimit` over integer seconds. */
const arbTimeLimit: fc.Arbitrary<TimeLimit> = fc
  .integer({ min: MIN_TIME_LIMIT_SECONDS, max: MAX_TIME_LIMIT_SECONDS })
  .map((seconds) => timeLimitOf(seconds));

/**
 * An arbitrary prior state over the given maze. Deliberately "dirty" so the
 * fresh session has something to leak if it were built carelessly: the avatar
 * sits on the exit (never the start), and Playing timers are drained and
 * running. Covers all three non-Idle variants (`Playing`, `Won`, `Lost`).
 */
function arbPriorState(maze: Maze): fc.Arbitrary<GameState> {
  const dirtyAvatar: Position = maze.exit;
  const playing: fc.Arbitrary<PlayingState> = fc
    .record({
      timeLimit: arbTimeLimit,
      remainingMs: fc.integer({ min: 0, max: 5000 }),
      timerStarted: fc.constant(true),
      moveInProgress: fc.boolean(),
    })
    .map((fields) => ({
      status: "Playing",
      maze,
      avatar: dirtyAvatar,
      timeLimit: fields.timeLimit,
      remainingMs: fields.remainingMs,
      timerStarted: fields.timerStarted,
      pausedElapsedMs: 0,
      moveInProgress: fields.moveInProgress,
    }));

  const won: fc.Arbitrary<WonState> = fc
    .record({
      timeLimit: arbTimeLimit,
      elapsedMs: fc.integer({ min: 0, max: 600_000 }),
    })
    .map((fields) => ({
      status: "Won",
      maze,
      avatar: dirtyAvatar,
      timeLimit: fields.timeLimit,
      elapsedMs: fields.elapsedMs,
    }));

  const lost: fc.Arbitrary<LostState> = arbTimeLimit.map((timeLimit) => ({
    status: "Lost",
    maze,
    avatar: dirtyAvatar,
    timeLimit,
    reason: "TimeExpired",
  }));

  return fc.oneof(playing, won, lost);
}

/** Assert a fresh session is fully reset and carries nothing from a prior run. */
function expectFreshSession(session: PlayingState, timeLimit: TimeLimit): void {
  expect(session.status).toBe("Playing");
  expect(session.avatar).toEqual(session.maze.start);
  expect(session.remainingMs).toBe(timeLimit * MILLISECONDS_PER_SECOND);
  expect(session.timerStarted).toBe(false);
  expect(session.moveInProgress).toBe(false);
}

describe("GameSessionFactory — Property 3: a fresh session resets avatar, timer, and status with no leaked state", () => {
  // Feature: maze-game, Property 3: A fresh session resets avatar, timer, and status with no leaked state
  it("createSession and StartSession always produce a fully reset session regardless of prior state", () => {
    fc.assert(
      fc.property(
        arbMaze.chain((maze) =>
          fc.record({
            maze: fc.constant(maze),
            timeLimit: arbTimeLimit,
            prior: arbPriorState(maze),
          }),
        ),
        ({ maze, timeLimit, prior }) => {
          // Path 1: the factory directly.
          const created = sessionFactory.createSession(maze, timeLimit);
          expectFreshSession(created, timeLimit);

          // Path 2: reduce's StartSession, starting from an arbitrary prior
          // state. The fresh session must ignore the prior avatar and timer.
          const started = reduce(prior, {
            type: "StartSession",
            config: { rows: maze.rows, columns: maze.columns, timeLimit },
          });
          expect(started.status).toBe("Playing");
          if (started.status !== "Playing") {
            return;
          }
          expectFreshSession(started, timeLimit);

          // No leaked state: even though the prior avatar sat on the exit, the
          // fresh avatar is on the start (they differ in a well-formed maze).
          expect(started.avatar).toEqual(maze.start);
          expect(started.avatar).not.toEqual(prior.avatar);
        },
      ),
      { numRuns: PROPERTY_MIN_RUNS },
    );
  });
});
