import fc from "fast-check";
import { describe, expect, it } from "vitest";

import { reduce } from "./reduce";
import { parseTimeLimit } from "./parseTimeLimit";
import { RecursiveBacktrackerGenerator } from "./RecursiveBacktrackerGenerator";
import {
  CellKind,
  type Direction,
  type GameState,
  type LostState,
  type Maze,
  type Position,
  type TimeLimit,
  type WonState,
} from "./types";

/**
 * Property-based test for Correctness Property 9.
 *
 * Property 9 (design.md): *For any* `WonState` or `LostState`, applying a
 * `Tick` action leaves the state unchanged, so the captured elapsed time and
 * outcome are retained.
 *
 * This is the frozen-timer guarantee behind R3.4 (on end, the timer stops and
 * retains its value) and R3.5 (a win stops the timer). Once the session has
 * ended, no `Tick` — regardless of how much time it reports — may advance the
 * timer, flip the outcome, or otherwise mutate the state. The task's focus is
 * the `Tick` case; we additionally assert a `Move` on an ended state is frozen
 * too, since the same freeze underlies R4.4.
 *
 * The invariants checked here are:
 *   1. `reduce(endedState, { type: "Tick", elapsedMs })` deep-equals the ended
 *      state for any non-negative `elapsedMs` (the primary property),
 *   2. the result is the very same object reference (a true no-op transition),
 *   3. `reduce(endedState, { type: "Move", direction })` is likewise frozen.
 *
 * Determinism (testing steering): the maze is generated by
 * `RecursiveBacktrackerGenerator` driven by a seeded mulberry32 rng, and every
 * choice (avatar path cell, elapsed/remaining values, direction) is derived
 * from fast-check arbitraries — no `Math.random`, no wall-clock time. The
 * property runs a minimum of 100 iterations.
 *
 * _Validates: Requirements 3.4, 3.5_
 */

const PROPERTY_MIN_RUNS = 100;
const MILLISECONDS_PER_SECOND = 1000;
const TIME_LIMIT_SECONDS = 60;

/** Upper bound for generated elapsed/win times: 600s (max time limit) in ms. */
const MAX_MS = 600 * MILLISECONDS_PER_SECOND;

/**
 * Upper bound for a generated `Tick` elapsed time. Chosen far larger than any
 * possible remaining time so a frozen state is exercised against ticks that
 * would, on a `Playing` state, overshoot and end the session.
 */
const MAX_TICK_ELAPSED_MS = 10 * MAX_MS;

const ALL_DIRECTIONS: ReadonlyArray<Direction> = [
  "Up",
  "Down",
  "Left",
  "Right",
];

/**
 * A tiny deterministic PRNG (mulberry32), matching the generator's test seed
 * helper. Given the same seed it yields the same sequence in `[0, 1)`, so maze
 * generation depends only on its injected inputs (no `Math.random`).
 */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A valid branded time limit, produced through the only validator that brands one. */
function timeLimit(seconds = TIME_LIMIT_SECONDS): TimeLimit {
  const result = parseTimeLimit(seconds);
  if (!result.ok) {
    throw new Error(`test fixture expected a valid time limit, got ${seconds}`);
  }
  return result.value;
}

/** Every path cell in the maze, in row-major order. */
function pathCells(maze: Maze): ReadonlyArray<Position> {
  const cells: Position[] = [];
  for (let row = 0; row < maze.rows; row += 1) {
    for (let column = 0; column < maze.columns; column += 1) {
      if (maze.grid[row]?.[column] === CellKind.Path) {
        cells.push({ row, column });
      }
    }
  }
  return cells;
}

/**
 * A generated ended state (`Won` or `Lost`) paired with a `Tick` elapsed time
 * and a `Move` direction to exercise the freeze against.
 */
interface EndedCase {
  readonly state: WonState | LostState;
  readonly tickElapsedMs: number;
  readonly moveDirection: Direction;
}

/**
 * Custom arbitrary for an ended state. It generates a valid maze from a seed,
 * places the avatar on some path cell (deterministically chosen from a further
 * integer), then builds either:
 *   - a `WonState` with an arbitrary captured `elapsedMs` in `[0, MAX_MS]`, or
 *   - a `LostState` with reason `"TimeExpired"`.
 * It also samples a non-negative `Tick` elapsed time (ranging well past any
 * remaining time) and a move direction.
 */
const endedCase: fc.Arbitrary<EndedCase> = fc
  .record({
    seed: fc.integer({ min: 0, max: 2 ** 31 - 1 }),
    rows: fc.integer({ min: 3, max: 12 }),
    columns: fc.integer({ min: 3, max: 12 }),
    cellPick: fc.nat(),
    won: fc.boolean(),
    elapsedMs: fc.integer({ min: 0, max: MAX_MS }),
    tickElapsedMs: fc.integer({ min: 0, max: MAX_TICK_ELAPSED_MS }),
    directionPick: fc.nat(),
  })
  .map(
    ({
      seed,
      rows,
      columns,
      cellPick,
      won,
      elapsedMs,
      tickElapsedMs,
      directionPick,
    }) => {
      const maze = new RecursiveBacktrackerGenerator().generate(
        rows,
        columns,
        mulberry32(seed),
      );

      const cells = pathCells(maze);
      // A generated maze always carves at least the start and exit path cells,
      // so `cells` is non-empty; the modulo pick is therefore well-defined.
      const avatar = cells[cellPick % cells.length]!;
      const moveDirection = ALL_DIRECTIONS[directionPick % ALL_DIRECTIONS.length]!;

      const base = { maze, avatar, timeLimit: timeLimit() };
      const state: WonState | LostState = won
        ? { status: "Won", ...base, elapsedMs }
        : { status: "Lost", ...base, reason: "TimeExpired" };

      return { state, tickElapsedMs, moveDirection };
    },
  );

describe("reduce — Property 9: ended sessions freeze the timer", () => {
  // Feature: maze-game, Property 9: Ended sessions freeze the timer
  it("returns Won/Lost states unchanged under any Tick (and Move)", () => {
    fc.assert(
      fc.property(endedCase, ({ state, tickElapsedMs, moveDirection }) => {
        // Snapshot before, to prove reduce mutated nothing in place.
        const snapshot: GameState = structuredClone(state);

        const afterTick = reduce(state, {
          type: "Tick",
          elapsedMs: tickElapsedMs,
        });

        // The primary property: an ended session freezes under Tick, so the
        // captured elapsed time / outcome is retained unchanged (R3.4, R3.5).
        expect(afterTick).toEqual(snapshot);
        // A true no-op transition returns the identical reference.
        expect(afterTick).toBe(state);

        // The same freeze underlies R4.4: a Move on an ended state is rejected
        // and leaves the state unchanged.
        const afterMove = reduce(state, {
          type: "Move",
          direction: moveDirection,
        });
        expect(afterMove).toEqual(snapshot);
        expect(afterMove).toBe(state);
      }),
      { numRuns: PROPERTY_MIN_RUNS },
    );
  });
});
