import fc from "fast-check";
import { describe, expect, it } from "vitest";

import { reduce } from "./reduce";
import { parseTimeLimit } from "./parseTimeLimit";
import { RecursiveBacktrackerGenerator } from "./RecursiveBacktrackerGenerator";
import {
  CellKind,
  type Direction,
  type GameState,
  type LostState,
  type Maze,
  type Position,
  type TimeLimit,
  type WonState,
} from "./types";

/**
 * Property-based test for Correctness Property 12.
 *
 * Property 12 (design.md): *For any* `WonState` or `LostState` and any
 * `Direction`, applying a `Move` leaves the state unchanged — the avatar
 * position and status are retained.
 *
 * This is the "input after session end" guarantee behind R4.4: once a
 * `Game_Session` has ended, the movement controller rejects every movement
 * command and leaves the avatar unchanged until a new session begins. In the
 * pure core that rule lives in `reduce`, which returns an ended state untouched
 * for a `Move` action (`resolveMove` short-circuits on any non-`Playing`
 * status).
 *
 * The invariants checked here are:
 *   1. `reduce(endedState, { type: "Move", direction })` deep-equals the ended
 *      state for any direction (the primary property),
 *   2. the result is the very same object reference (a true no-op transition),
 *   3. `reduce` mutated nothing in place (verified against a pre-call snapshot).
 *
 * Determinism (testing steering): the maze is generated by
 * `RecursiveBacktrackerGenerator` driven by a seeded mulberry32 rng, and every
 * choice (avatar path cell, Won elapsed time, Lost reason, direction) is
 * derived from fast-check arbitraries — no `Math.random`, no wall-clock time.
 * The property runs a minimum of 100 iterations.
 *
 * _Validates: Requirements 4.4_
 */

const PROPERTY_MIN_RUNS = 100;
const MILLISECONDS_PER_SECOND = 1000;
const TIME_LIMIT_SECONDS = 60;

/** Upper bound for a generated Won elapsed time: 600s (max time limit) in ms. */
const MAX_MS = 600 * MILLISECONDS_PER_SECOND;

const ALL_DIRECTIONS: ReadonlyArray<Direction> = [
  "Up",
  "Down",
  "Left",
  "Right",
];

/**
 * A tiny deterministic PRNG (mulberry32), matching the generator's test seed
 * helper. Given the same seed it yields the same sequence in `[0, 1)`, so maze
 * generation depends only on its injected inputs (no `Math.random`).
 */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A valid branded time limit, produced through the only validator that brands one. */
function timeLimit(seconds = TIME_LIMIT_SECONDS): TimeLimit {
  const result = parseTimeLimit(seconds);
  if (!result.ok) {
    throw new Error(`test fixture expected a valid time limit, got ${seconds}`);
  }
  return result.value;
}

/** Every path cell in the maze, in row-major order. */
function pathCells(maze: Maze): ReadonlyArray<Position> {
  const cells: Position[] = [];
  for (let row = 0; row < maze.rows; row += 1) {
    for (let column = 0; column < maze.columns; column += 1) {
      if (maze.grid[row]?.[column] === CellKind.Path) {
        cells.push({ row, column });
      }
    }
  }
  return cells;
}

/**
 * A generated ended state (`Won` or `Lost`) paired with a `Move` direction to
 * exercise the rejection against.
 */
interface EndedMoveCase {
  readonly state: WonState | LostState;
  readonly direction: Direction;
}

/**
 * Custom arbitrary for an ended state plus a move. It generates a valid maze
 * from a seed, places the avatar on some path cell (deterministically chosen
 * from a further integer), then builds either:
 *   - a `WonState` with an arbitrary captured `elapsedMs` in `[0, MAX_MS]`, or
 *   - a `LostState` with reason `"TimeExpired"`,
 * and samples a move direction.
 */
const endedMoveCase: fc.Arbitrary<EndedMoveCase> = fc
  .record({
    seed: fc.integer({ min: 0, max: 2 ** 31 - 1 }),
    rows: fc.integer({ min: 3, max: 12 }),
    columns: fc.integer({ min: 3, max: 12 }),
    cellPick: fc.nat(),
    won: fc.boolean(),
    elapsedMs: fc.integer({ min: 0, max: MAX_MS }),
    directionPick: fc.nat(),
  })
  .map(({ seed, rows, columns, cellPick, won, elapsedMs, directionPick }) => {
    const maze = new RecursiveBacktrackerGenerator().generate(
      rows,
      columns,
      mulberry32(seed),
    );

    const cells = pathCells(maze);
    // A generated maze always carves at least the start and exit path cells,
    // so `cells` is non-empty; the modulo pick is therefore well-defined.
    const avatar = cells[cellPick % cells.length]!;
    const direction = ALL_DIRECTIONS[directionPick % ALL_DIRECTIONS.length]!;

    const base = { maze, avatar, timeLimit: timeLimit() };
    const state: WonState | LostState = won
      ? { status: "Won", ...base, elapsedMs }
      : { status: "Lost", ...base, reason: "TimeExpired" };

    return { state, direction };
  });

describe("reduce — Property 12: moves after the session ends are rejected", () => {
  // Feature: maze-game, Property 12: Any move after the session ends is rejected
  it("returns Won/Lost states unchanged under any Move direction", () => {
    fc.assert(
      fc.property(endedMoveCase, ({ state, direction }) => {
        // Snapshot before, to prove reduce mutated nothing in place.
        const snapshot: GameState = structuredClone(state);

        const afterMove = reduce(state, { type: "Move", direction });

        // The primary property: a Move on an ended session is rejected and the
        // avatar position / status / outcome are retained unchanged (R4.4).
        expect(afterMove).toEqual(snapshot);
        // A true no-op transition returns the identical reference.
        expect(afterMove).toBe(state);
      }),
      { numRuns: PROPERTY_MIN_RUNS },
    );
  });
});
