import fc from "fast-check";
import { describe, expect, it } from "vitest";

import { resolveMove } from "./resolveMove";
import { parseTimeLimit } from "./parseTimeLimit";
import { RecursiveBacktrackerGenerator } from "./RecursiveBacktrackerGenerator";
import {
  CellKind,
  type Direction,
  type Maze,
  type PlayingState,
  type Position,
  type TimeLimit,
} from "./types";

/**
 * Property-based test for Correctness Property 10.
 *
 * Property 10 (design.md): *For any* `PlayingState` whose `remainingMs` is
 * greater than zero and any `Direction` whose target is the exit cell,
 * `resolveMove` transitions the state to `Won` and records an `elapsedMs`
 * equal to the elapsed time accumulated for the session.
 *
 * The generated case places the avatar on a path cell that is orthogonally
 * adjacent to the exit and points the move at the exit, with `remainingMs`
 * sampled in `(0, timeLimit * 1000]`. The expected outcome is a `WonState`
 * whose avatar equals the exit and whose `elapsedMs` equals
 * `timeLimit * 1000 - remainingMs` (the session's accumulated elapsed time).
 *
 * Determinism (testing steering): the maze is generated by
 * `RecursiveBacktrackerGenerator` driven by a seeded mulberry32 rng, and every
 * choice (adjacent cell, remaining time) is derived from fast-check integers —
 * no `Math.random`, no wall-clock time. The property runs a minimum of 100
 * iterations.
 *
 * _Validates: Requirements 4.1, 4.2, 3.5_
 */

const PROPERTY_MIN_RUNS = 100;
const MILLISECONDS_PER_SECOND = 1000;
const TIME_LIMIT_SECONDS = 60;

/** Row/column delta for each direction. */
const DIRECTION_DELTAS: Readonly<Record<Direction, Position>> = {
  Up: { row: -1, column: 0 },
  Down: { row: 1, column: 0 },
  Left: { row: 0, column: -1 },
  Right: { row: 0, column: 1 },
};

const ALL_DIRECTIONS: ReadonlyArray<Direction> = [
  "Up",
  "Down",
  "Left",
  "Right",
];

/**
 * A tiny deterministic PRNG (mulberry32), matching the generator's test seed
 * helper. Given the same seed it yields the same sequence in `[0, 1)`, so maze
 * generation depends only on its injected inputs (no `Math.random`).
 */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A 60-second limit produced through the only validator that brands one. */
function timeLimit(seconds = TIME_LIMIT_SECONDS): TimeLimit {
  const result = parseTimeLimit(seconds);
  if (!result.ok) {
    throw new Error(`test fixture expected a valid time limit, got ${seconds}`);
  }
  return result.value;
}

function cellAt(maze: Maze, position: Position): CellKind | undefined {
  return maze.grid[position.row]?.[position.column];
}

function isPath(maze: Maze, position: Position): boolean {
  return cellAt(maze, position) === CellKind.Path;
}

function isExit(maze: Maze, position: Position): boolean {
  return position.row === maze.exit.row && position.column === maze.exit.column;
}

/**
 * A generated, winning move: a `PlayingState` whose avatar sits on a path cell
 * orthogonally adjacent to the exit, together with the direction that steps
 * onto the exit. `remainingMs > 0` guarantees the win transition.
 */
interface WinningMoveCase {
  readonly state: PlayingState;
  readonly direction: Direction;
  readonly expectedElapsedMs: number;
}

/**
 * Every path cell that is orthogonally adjacent to the exit, paired with the
 * single direction that steps from that cell onto the exit. A generated maze
 * guarantees the exit has at least one carved path neighbor, so this is
 * non-empty.
 */
function cellsAdjacentToExit(
  maze: Maze,
): ReadonlyArray<{ readonly from: Position; readonly direction: Direction }> {
  const cells: { from: Position; direction: Direction }[] = [];
  for (const direction of ALL_DIRECTIONS) {
    const delta = DIRECTION_DELTAS[direction];
    // `from` is the cell that, moving in `direction`, lands on the exit.
    const from: Position = {
      row: maze.exit.row - delta.row,
      column: maze.exit.column - delta.column,
    };
    if (isPath(maze, from) && !isExit(maze, from)) {
      cells.push({ from, direction });
    }
  }
  return cells;
}

/**
 * Custom arbitrary for a valid, winning move. It generates a valid maze from a
 * seed, picks (deterministically from further integers) a path cell adjacent
 * to the exit and the direction onto the exit, and samples `remainingMs` in
 * `(0, timeLimit * 1000]`.
 */
const winningMoveCase: fc.Arbitrary<WinningMoveCase> = fc
  .record({
    seed: fc.integer({ min: 0, max: 2 ** 31 - 1 }),
    rows: fc.integer({ min: 3, max: 12 }),
    columns: fc.integer({ min: 3, max: 12 }),
    cellPick: fc.nat(),
    remainingMs: fc.integer({
      min: 1,
      max: TIME_LIMIT_SECONDS * MILLISECONDS_PER_SECOND,
    }),
  })
  .map(({ seed, rows, columns, cellPick, remainingMs }) => {
    const maze = new RecursiveBacktrackerGenerator().generate(
      rows,
      columns,
      mulberry32(seed),
    );

    const candidates = cellsAdjacentToExit(maze);
    // The exit is a carved path cell with at least one path neighbor, so
    // candidates is non-empty; guard anyway for a clear failure message.
    const cell = candidates[cellPick % candidates.length]!;

    const state: PlayingState = {
      status: "Playing",
      maze,
      avatar: cell.from,
      timeLimit: timeLimit(),
      remainingMs,
      timerStarted: true,
      pausedElapsedMs: 0,
      moveInProgress: false,
    };

    const expectedElapsedMs =
      TIME_LIMIT_SECONDS * MILLISECONDS_PER_SECOND - remainingMs;

    return { state, direction: cell.direction, expectedElapsedMs };
  });

describe("resolveMove — Property 10: reaching the exit with time remaining wins and captures elapsed time", () => {
  // Feature: maze-game, Property 10: Reaching the exit with time remaining wins and captures elapsed time
  it("transitions to Won at the exit with captured elapsed time", () => {
    fc.assert(
      fc.property(
        winningMoveCase,
        ({ state, direction, expectedElapsedMs }) => {
          const next = resolveMove(state, direction);

          // Reaching the exit with time remaining is a win (R4.1).
          expect(next.status).toBe("Won");

          // The avatar lands exactly on the exit cell.
          expect(next.avatar).toEqual(state.maze.exit);

          // Elapsed time captured equals the session's accumulated elapsed
          // time: timeLimit * 1000 - remainingMs (R4.2, R3.5).
          if (next.status === "Won") {
            expect(next.elapsedMs).toBe(expectedElapsedMs);
          }
        },
      ),
      { numRuns: PROPERTY_MIN_RUNS },
    );
  });
});
