import fc from "fast-check";
import { describe, expect, it } from "vitest";

import { resolveMove } from "./resolveMove";
import { RecursiveBacktrackerGenerator } from "./RecursiveBacktrackerGenerator";
import {
  CellKind,
  type Direction,
  type Maze,
  type PlayingState,
  type Position,
  type TimeLimit,
} from "./types";

/**
 * Property-based test for Correctness Property 5.
 *
 * The design's Property 5 states: for any `PlayingState` and any `Direction`,
 * a move into a wall or off the grid leaves the avatar unchanged, so the avatar
 * position is *always* an in-bounds Path cell after `resolveMove` — whether the
 * move was accepted (advances onto a Path cell, R2.1) or blocked (unchanged,
 * still on its original Path cell, R2.2/R2.3). This test asserts that invariant
 * over generated mazes, avatar placements, and directions.
 *
 * Per the testing steering, one fast-check property realizes the design
 * property, running a minimum of 100 iterations with custom arbitraries that
 * constrain generation to the valid input space: a real generated (valid) maze,
 * a `PlayingState` whose avatar sits on a random Path cell of that maze, and an
 * arbitrary `Direction`. Randomness enters only through an injected seeded PRNG
 * (mulberry32) so a failing run is reproducible from its seed; `Math.random`
 * is never used directly. The result may be `Playing` (blocked or advanced) or
 * `Won` (advanced onto the exit) — in every variant the avatar must be a valid
 * in-bounds Path cell, which is what the invariant checks.
 *
 * _Validates: Requirements 2.2, 2.3_
 */

/** fast-check iterations; testing steering requires a minimum of 100. */
const NUM_RUNS = 100;

/** Smallest dimension for which the generator yields distinct start/exit. */
const MIN_DIMENSION = 3;
/** Upper dimension bound; keeps the property fast at ≥ 100 iterations. */
const MAX_DIMENSION = 15;

/** A branded 60s limit; the exact value is irrelevant to this position invariant. */
const TIME_LIMIT_SECONDS = 60;
const MILLISECONDS_PER_SECOND = 1000;

const ALL_DIRECTIONS: readonly Direction[] = ["Up", "Down", "Left", "Right"];

/**
 * A tiny deterministic PRNG (mulberry32): the same seed yields the same
 * sequence in `[0, 1)`, making maze generation and avatar placement
 * reproducible without `Math.random`. Defined locally per the testing steering.
 */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Every Path cell in the maze; the avatar can legitimately occupy any of these. */
function pathCells(maze: Maze): readonly Position[] {
  const cells: Position[] = [];
  for (let row = 0; row < maze.rows; row++) {
    for (let column = 0; column < maze.columns; column++) {
      if (maze.grid[row]?.[column] === CellKind.Path) {
        cells.push({ row, column });
      }
    }
  }
  return cells;
}

/** True when `position` is inside the grid AND on a Path cell. */
function isInBoundsPathCell(maze: Maze, position: Position): boolean {
  const inBounds =
    position.row >= 0 &&
    position.row < maze.rows &&
    position.column >= 0 &&
    position.column < maze.columns;
  return inBounds && maze.grid[position.row]?.[position.column] === CellKind.Path;
}

/** Build a Playing state with the avatar on the given Path cell. */
function playingWithAvatar(maze: Maze, avatar: Position): PlayingState {
  const timeLimit = TIME_LIMIT_SECONDS as TimeLimit;
  return {
    status: "Playing",
    maze,
    avatar,
    timeLimit,
    remainingMs: TIME_LIMIT_SECONDS * MILLISECONDS_PER_SECOND,
    timerStarted: false,
    pausedElapsedMs: 0,
    moveInProgress: false,
  };
}

const dimensionArb = fc.integer({ min: MIN_DIMENSION, max: MAX_DIMENSION });
/** Full 32-bit seed space for the injected PRNG. */
const seedArb = fc.integer({ min: 0, max: 0xffffffff });
/** A unit fraction used to pick one Path cell independently of the maze seed. */
const cellFractionArb = fc.double({ min: 0, max: 1, noNaN: true, maxExcluded: true });
const directionArb = fc.constantFrom(...ALL_DIRECTIONS);

/**
 * Custom arbitrary: a valid `PlayingState` (avatar on a random Path cell) paired
 * with an arbitrary `Direction`. The maze is generated by the real generator so
 * it is guaranteed valid; the avatar is chosen from the maze's own Path cells,
 * exercising both accepted and blocked moves as the direction varies.
 */
const playingStateAndDirectionArb = fc
  .record({
    rows: dimensionArb,
    columns: dimensionArb,
    seed: seedArb,
    cellFraction: cellFractionArb,
    direction: directionArb,
  })
  .map(({ rows, columns, seed, cellFraction, direction }) => {
    const generator = new RecursiveBacktrackerGenerator();
    const maze = generator.generate(rows, columns, mulberry32(seed));
    const cells = pathCells(maze);
    const index = Math.min(cells.length - 1, Math.floor(cellFraction * cells.length));
    const avatar = cells[index] ?? maze.start;
    return { state: playingWithAvatar(maze, avatar), direction };
  });

describe("resolveMove — Property 5: the avatar never enters a wall or out-of-bounds cell", () => {
  // Feature: maze-game, Property 5: The avatar never enters a wall or out-of-bounds cell
  it("keeps the avatar on an in-bounds Path cell for any state and any direction", () => {
    fc.assert(
      fc.property(playingStateAndDirectionArb, ({ state, direction }) => {
        const next = resolveMove(state, direction);

        expect(isInBoundsPathCell(state.maze, next.avatar)).toBe(true);
      }),
      { numRuns: NUM_RUNS },
    );
  });
});
