import fc from "fast-check";
import { describe, expect, it } from "vitest";

import { resolveMove } from "./resolveMove";
import { parseTimeLimit } from "./parseTimeLimit";
import { RecursiveBacktrackerGenerator } from "./RecursiveBacktrackerGenerator";
import {
  CellKind,
  type Direction,
  type Maze,
  type PlayingState,
  type Position,
  type TimeLimit,
} from "./types";

/**
 * Property-based test for Correctness Property 4.
 *
 * Property 4 (design.md): *For any* `PlayingState` (with no move in progress)
 * and any `Direction` whose target cell is inside the grid and is a path cell,
 * `resolveMove` moves the avatar exactly one cell in that direction and to no
 * other cell.
 *
 * This test constrains generation to a *valid* move that is deliberately NOT
 * onto the exit, so the expected outcome is a pure one-cell advance that stays
 * `Playing` (moving onto the exit with time remaining would win — Property 10
 * covers that). The invariant checked is therefore: the new avatar equals the
 * old avatar plus the direction's delta (Manhattan distance 1) and the status
 * remains `Playing`.
 *
 * Determinism (testing steering): the maze is generated by
 * `RecursiveBacktrackerGenerator` driven by a seeded mulberry32 rng, and every
 * choice (cell, direction) is derived from fast-check integers — no
 * `Math.random`. The property runs a minimum of 100 iterations.
 *
 * _Validates: Requirements 2.1_
 */

const PROPERTY_MIN_RUNS = 100;
const MILLISECONDS_PER_SECOND = 1000;

/** Row/column delta for each direction — the expected one-cell advance. */
const DIRECTION_DELTAS: Readonly<Record<Direction, Position>> = {
  Up: { row: -1, column: 0 },
  Down: { row: 1, column: 0 },
  Left: { row: 0, column: -1 },
  Right: { row: 0, column: 1 },
};

const ALL_DIRECTIONS: ReadonlyArray<Direction> = [
  "Up",
  "Down",
  "Left",
  "Right",
];

/**
 * A tiny deterministic PRNG (mulberry32), matching the generator's test seed
 * helper. Given the same seed it yields the same sequence in `[0, 1)`, so maze
 * generation depends only on its injected inputs (no `Math.random`).
 */
function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A 60-second limit produced through the only validator that brands one. */
function timeLimit(seconds = 60): TimeLimit {
  const result = parseTimeLimit(seconds);
  if (!result.ok) {
    throw new Error(`test fixture expected a valid time limit, got ${seconds}`);
  }
  return result.value;
}

function cellAt(maze: Maze, position: Position): CellKind | undefined {
  return maze.grid[position.row]?.[position.column];
}

function isPath(maze: Maze, position: Position): boolean {
  return cellAt(maze, position) === CellKind.Path;
}

function isExit(maze: Maze, position: Position): boolean {
  return position.row === maze.exit.row && position.column === maze.exit.column;
}

/**
 * A generated, valid move: a `PlayingState` whose avatar sits on a path cell
 * that has at least one in-bounds, non-exit path neighbor, together with a
 * direction leading to such a neighbor. Restricting to non-exit targets keeps
 * the expected result a plain one-cell advance rather than a win.
 */
interface ValidMoveCase {
  readonly state: PlayingState;
  readonly direction: Direction;
  readonly expectedTarget: Position;
}

/**
 * Every path cell that owns at least one valid (in-bounds, non-exit path)
 * neighbor, paired with the directions that reach those neighbors.
 */
function movablePathCells(
  maze: Maze,
): ReadonlyArray<{ readonly from: Position; readonly directions: Direction[] }> {
  const cells: { from: Position; directions: Direction[] }[] = [];
  for (let row = 0; row < maze.rows; row += 1) {
    for (let column = 0; column < maze.columns; column += 1) {
      const from: Position = { row, column };
      if (!isPath(maze, from) || isExit(maze, from)) {
        continue;
      }
      const directions = ALL_DIRECTIONS.filter((direction) => {
        const delta = DIRECTION_DELTAS[direction];
        const target: Position = {
          row: row + delta.row,
          column: column + delta.column,
        };
        return isPath(maze, target) && !isExit(maze, target);
      });
      if (directions.length > 0) {
        cells.push({ from, directions });
      }
    }
  }
  return cells;
}

/**
 * Custom arbitrary for a valid, non-winning move. It generates a valid maze
 * from a seed, then picks (deterministically from further integers) an avatar
 * cell and a direction that together form a valid one-cell advance onto a
 * non-exit path cell.
 */
const validMoveCase: fc.Arbitrary<ValidMoveCase> = fc
  .record({
    seed: fc.integer({ min: 0, max: 2 ** 31 - 1 }),
    rows: fc.integer({ min: 3, max: 12 }),
    columns: fc.integer({ min: 3, max: 12 }),
    cellPick: fc.nat(),
    directionPick: fc.nat(),
    remainingMs: fc.integer({ min: 1, max: 600 * MILLISECONDS_PER_SECOND }),
  })
  .map(({ seed, rows, columns, cellPick, directionPick, remainingMs }) => {
    const maze = new RecursiveBacktrackerGenerator().generate(
      rows,
      columns,
      mulberry32(seed),
    );

    const candidates = movablePathCells(maze);
    // A generated maze always has at least the start cell with a carved
    // neighbor, so candidates is non-empty; guard anyway for a clear failure.
    const cell = candidates[cellPick % candidates.length]!;
    const direction = cell.directions[directionPick % cell.directions.length]!;
    const delta = DIRECTION_DELTAS[direction];
    const expectedTarget: Position = {
      row: cell.from.row + delta.row,
      column: cell.from.column + delta.column,
    };

    const state: PlayingState = {
      status: "Playing",
      maze,
      avatar: cell.from,
      timeLimit: timeLimit(),
      remainingMs,
      timerStarted: true,
      pausedElapsedMs: 0,
      moveInProgress: false,
    };

    return { state, direction, expectedTarget };
  });

describe("resolveMove — Property 4: a valid move advances the avatar exactly one cell", () => {
  // Feature: maze-game, Property 4: A valid move advances the avatar exactly one cell
  it("moves the avatar exactly one cell in the chosen direction and nowhere else", () => {
    fc.assert(
      fc.property(validMoveCase, ({ state, direction, expectedTarget }) => {
        const next = resolveMove(state, direction);

        // Stays Playing: a non-exit target is not a win or loss transition.
        expect(next.status).toBe("Playing");

        // Advances to exactly the target one cell away in `direction`.
        expect(next.avatar).toEqual(expectedTarget);

        // Manhattan distance from the origin is exactly one cell.
        const stepped =
          Math.abs(next.avatar.row - state.avatar.row) +
          Math.abs(next.avatar.column - state.avatar.column);
        expect(stepped).toBe(1);
      }),
      { numRuns: PROPERTY_MIN_RUNS },
    );
  });
});
